import { beforeAll, expect, it } from 'vitest';
import type { PGlite } from '@electric-sql/pglite';
import { crearDbLocal } from '../../scripts/db/pglite';
import { comoUsuario, crearUsuario } from './utilidades';
import { crearInsumo, idTamano } from './fabricas';
let db: PGlite, operaciones: string, finanzas: string, compras: string, ingrediente: string, tamano: string;
beforeAll(async () => { db = await crearDbLocal(); operaciones = await crearUsuario(db, 'operaciones'); finanzas = await crearUsuario(db, 'finanzas'); compras = await crearUsuario(db, 'compras'); ingrediente = await crearInsumo(db, { nombre: 'RPC Café', costoPaquete: 100, presentacion: 1000 }); tamano = await idTamano(db, 'Único'); });
async function datos(nombre: string) { const c = await db.query<{ id: string }>(`insert into categorias_producto(nombre) values($1) returning id`, [nombre]); return { nombre, tipo: 'producto', categoria_id: c.rows[0].id, tamanos: [tamano], lineas: [{ insumo_id: ingrediente, subreceta_id: null, orden: 0, cantidades: [{ tamano_id: tamano, cantidad: 10 }] }] }; }
async function guardar(uid: string, d: unknown) { return comoUsuario(db, uid, async () => (await db.query<{ r: { id: string; version: number } }>('select guardar_receta($1::jsonb) as r', [JSON.stringify(d)])).rows[0].r); }
it('guarda cabecera, tamaños, líneas y costo en una sola llamada', async () => { const d = await datos('RPC Alta'); const r = await guardar(operaciones, d); expect(r.version).toBeGreaterThan(1); const costo = await db.query<{ costo: string }>('select costo from v_costo_producto where producto_id=$1', [r.id]); expect(Number(costo.rows[0].costo)).toBe(1); });
it('rechaza roles ajenos y perfiles inactivos', async () => { const d = await datos('RPC Denegado'); for (const uid of [compras, finanzas]) await expect(guardar(uid, d)).rejects.toThrow(/permiso/); const inactivo = await crearUsuario(db, 'operaciones'); await db.query('update perfiles set activo=false where user_id=$1', [inactivo]); await expect(guardar(inactivo, d)).rejects.toThrow(/permiso/); });
it('revierte datos y bitácora por cantidad inválida', async () => { const d = await datos('RPC Rollback'); d.lineas[0].cantidades[0].cantidad = -1; const antes = await db.query<{ n: number }>('select count(*)::int n from bitacora'); await expect(guardar(operaciones, d)).rejects.toThrow(); expect((await db.query('select id from recetas where nombre=$1', [d.nombre])).rows).toHaveLength(0); expect((await db.query<{ n: number }>('select count(*)::int n from bitacora')).rows[0].n).toBe(antes.rows[0].n); });
it('detecta versión vieja después de escritura directa y conserva precios', async () => { const d = await datos('RPC Version'); const r = await guardar(operaciones, d); await comoUsuario(db, finanzas, () => db.query('update producto_tamanos set precio_lista=50 where producto_id=$1', [r.id])); await expect(guardar(operaciones, { ...d, ...r })).rejects.toThrow(/cambió/); const version = (await db.query<{ version: number }>('select version from recetas where id=$1', [r.id])).rows[0].version; await guardar(operaciones, { ...d, id: r.id, version }); expect(Number((await db.query<{ precio_lista: string }>('select precio_lista from producto_tamanos where producto_id=$1', [r.id])).rows[0].precio_lista)).toBe(50); });
it('no permite enviar precios ni líneas ajenas', async () => { const d = await datos('RPC Campos'); await expect(guardar(operaciones, { ...d, precio_lista: 40 })).rejects.toThrow(/precios/); const r = await guardar(operaciones, d); const l = (await db.query<{ id: string }>('select id from receta_lineas where receta_id=$1', [r.id])).rows[0].id; const otra = await datos('RPC Ajena'); await expect(guardar(operaciones, { ...otra, lineas: [{ ...otra.lineas[0], id: l }] })).rejects.toThrow(/pertenece/); });
it('anon no ejecuta la RPC', async () => { await db.exec('set role anon'); try { await expect(db.query(`select guardar_receta('{}')`)).rejects.toThrow(/permission denied/); } finally { await db.exec('reset role'); } });
